import type { Quote } from "@/types/shipping";

const formatUSD = (n: number) =>
  "$" + new Intl.NumberFormat("en-US", { minimumFractionDigits: 0 }).format(Math.round(n));

const formatVND = (n: number) =>
  new Intl.NumberFormat("vi-VN").format(n) + " ₫";

export function openPrintWindow(title: string, bodyHtml: string) {
  const w = window.open("", "_blank");
  if (!w) return;
  w.document.write(`<!DOCTYPE html>
<html>
<head>
  <title>${title}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Arial, sans-serif; font-size: 13px; color: #111; padding: 48px; }
    h1 { font-size: 20px; font-weight: 700; border-bottom: 2px solid #111; padding-bottom: 10px; margin-bottom: 20px; }
    h2 { font-size: 13px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em;
         color: #6b7280; margin: 20px 0 8px; }
    .draft-watermark { position: fixed; top: 40%; left: 50%; transform: translate(-50%,-50%) rotate(-30deg);
         font-size: 96px; font-weight: 900; color: rgba(0,0,0,0.06); pointer-events: none; z-index: 0; }
    .meta-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 24px; }
    .meta-block p { font-size: 12px; color: #6b7280; margin-bottom: 2px; }
    .meta-block strong { font-size: 13px; color: #111; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; }
    th { background: #f3f4f6; text-align: left; padding: 8px 12px;
         border: 1px solid #d1d5db; font-size: 12px; text-transform: uppercase; letter-spacing: 0.04em; }
    td { padding: 8px 12px; border: 1px solid #d1d5db; vertical-align: top; }
    .text-right { text-align: right; }
    .total-row td { font-weight: 700; background: #f9fafb; }
    .footer { margin-top: 48px; padding-top: 12px; border-top: 1px solid #e5e7eb;
              font-size: 11px; color: #9ca3af; display: flex; justify-content: space-between; }
    .signature-block { margin-top: 64px; }
    .signature-line { border-top: 1px solid #111; width: 240px; margin-top: 48px; padding-top: 6px;
                      font-size: 12px; color: #374151; }
    @media print { .no-print { display: none; } }
  </style>
</head>
<body>
  ${bodyHtml}
  <div class="footer">
    <span>Generated by TBP Auto CRM</span>
    <span>${new Date().toLocaleString()}</span>
  </div>
  <div class="no-print" style="margin-top:32px">
    <button onclick="window.print()"
      style="background:#2563eb;color:#fff;border:none;padding:10px 24px;border-radius:6px;font-size:14px;cursor:pointer">
      🖨 Print this document
    </button>
  </div>
</body>
</html>`);
  w.document.close();
}

export function printCommercialInvoice(quote: Quote, isDraft = true) {
  const title = `${isDraft ? "DRAFT " : ""}Commercial Invoice – ${quote.id}`;
  const draftBadge = isDraft
    ? '<span style="background:#fef3c7;color:#92400e;padding:2px 10px;border-radius:4px;font-size:12px;font-weight:700;margin-left:10px">DRAFT</span>'
    : "";
  const totalUsd = (quote.leg2_total_usd ?? 0) + (quote.leg3_estimate_usd ?? 0);

  openPrintWindow(
    title,
    `
    ${isDraft ? '<div class="draft-watermark">DRAFT</div>' : ""}
    <h1>COMMERCIAL INVOICE ${draftBadge}</h1>

    <div class="meta-grid">
      <div class="meta-block">
        <p>Seller</p>
        <strong>TBP Auto Co., Ltd.</strong><br>
        <span style="font-size:12px;color:#374151">Hai Phong Industrial Zone, Vietnam<br>
        Tel: +84-225-xxx-xxxx | VAT: xxxxxxxxxx</span>
      </div>
      <div class="meta-block">
        <p>Invoice No.</p><strong>${quote.id}-CI</strong><br>
        <p style="margin-top:6px">Date</p><strong>${new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })}</strong><br>
        <p style="margin-top:6px">Incoterms</p><strong>${quote.incoterm} – ${quote.dest_port}</strong>
      </div>
      <div class="meta-block">
        <p>Buyer / Consignee</p>
        <strong>${quote.customer_name}</strong><br>
        <span style="font-size:12px;color:#374151">
          ${quote.contact_email ?? ""}<br>
          ${quote.delivery_address ?? ""}, ${quote.delivery_state ?? ""}
        </span>
      </div>
      <div class="meta-block">
        <p>Port of Loading</p><strong>Hai Phong, Vietnam (VNHPH)</strong><br>
        <p style="margin-top:6px">Port of Discharge</p><strong>${quote.dest_port}</strong><br>
        <p style="margin-top:6px">B/L No.</p><strong>${quote.bl_number ?? "TBD"}</strong><br>
        <p style="margin-top:6px">ETD</p><strong>${quote.etd ?? "TBD"}</strong>
      </div>
    </div>

    <h2>Description of Goods</h2>
    <table>
      <tr>
        <th>Description of Goods</th>
        <th>HS Code</th>
        <th>Country of Origin</th>
        <th class="text-right">Total Amount (USD)</th>
      </tr>
      <tr>
        <td>${quote.products ?? "Auto Parts"}</td>
        <td>8708.xx</td>
        <td>Vietnam</td>
        <td class="text-right">${formatUSD(totalUsd)}</td>
      </tr>
      <tr class="total-row">
        <td colspan="3" class="text-right">Total USD</td>
        <td class="text-right">${formatUSD(totalUsd)}</td>
      </tr>
    </table>

    <div class="signature-block">
      <div class="signature-line">Authorized Signature & Company Stamp<br>TBP Auto Co., Ltd.</div>
    </div>
  `
  );
}

export function printPackingList(quote: Quote, isDraft = true) {
  const title = `${isDraft ? "DRAFT " : ""}Packing List – ${quote.id}`;

  openPrintWindow(
    title,
    `
    ${isDraft ? '<div class="draft-watermark">DRAFT</div>' : ""}
    <h1>PACKING LIST ${isDraft ? '<span style="background:#fef3c7;color:#92400e;padding:2px 10px;border-radius:4px;font-size:12px;font-weight:700;margin-left:10px">DRAFT</span>' : ""}</h1>

    <div class="meta-grid">
      <div class="meta-block">
        <p>Shipper / Exporter</p><strong>TBP Auto Co., Ltd.</strong><br>
        <span style="font-size:12px;color:#374151">Hai Phong Industrial Zone, Vietnam</span>
      </div>
      <div class="meta-block">
        <p>Consignee</p><strong>${quote.customer_name}</strong><br>
        <span style="font-size:12px;color:#374151">${quote.delivery_address ?? ""}, ${quote.delivery_state ?? ""}</span>
      </div>
      <div class="meta-block">
        <p>Invoice Reference</p><strong>${quote.id}-CI</strong><br>
        <p style="margin-top:6px">Port of Loading</p><strong>Hai Phong (VNHPH)</strong>
      </div>
      <div class="meta-block">
        <p>Port of Discharge</p><strong>${quote.dest_port}</strong><br>
        <p style="margin-top:6px">Container Type</p><strong>${quote.container_type}</strong><br>
        <p style="margin-top:6px">Carrier</p><strong>${quote.carrier ?? "TBD"}</strong>
      </div>
    </div>

    <h2>Packing Details</h2>
    <table>
      <tr>
        <th>Marks & Numbers</th>
        <th>Description</th>
        <th>No. of Pkgs</th>
        <th>Net Weight (kg)</th>
        <th>Gross Weight (kg)</th>
        <th>Measurement (CBM)</th>
      </tr>
      <tr>
        <td>${isDraft ? "TBD" : quote.id}</td>
        <td>${quote.products ?? "Auto Parts"}</td>
        <td>TBD</td>
        <td>TBD</td>
        <td>TBD</td>
        <td>TBD</td>
      </tr>
      <tr class="total-row">
        <td colspan="2">TOTAL</td>
        <td>TBD</td>
        <td>TBD</td>
        <td>TBD</td>
        <td>TBD</td>
      </tr>
    </table>
    ${isDraft ? '<p style="margin-top:16px;font-size:12px;color:#6b7280;font-style:italic">⚠ This is a DRAFT packing list. Weights and measurements to be confirmed on cargo ready date.</p>' : ""}

    <div class="signature-block">
      <div class="signature-line">Prepared by – TBP Auto Co., Ltd.</div>
    </div>
  `
  );
}

export function printOutputInvoice(quote: Quote) {
  const leg2 = quote.leg2_total_usd ?? 0;
  const leg3 = quote.leg3_estimate_usd ?? 0;

  openPrintWindow(
    `Output Invoice – ${quote.id}`,
    `
    <h1>INVOICE</h1>

    <div class="meta-grid">
      <div class="meta-block">
        <p>From (Seller)</p><strong>TBP Auto Co., Ltd.</strong><br>
        <span style="font-size:12px;color:#374151">Hai Phong Industrial Zone, Vietnam</span>
      </div>
      <div class="meta-block">
        <p>Invoice No.</p><strong>${quote.id}-OUT</strong><br>
        <p style="margin-top:6px">Date</p>
        <strong>${new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })}</strong>
      </div>
      <div class="meta-block">
        <p>To (Buyer)</p><strong>${quote.customer_name}</strong><br>
        <span style="font-size:12px;color:#374151">${quote.contact_email ?? ""}<br>${quote.delivery_address ?? ""}</span>
      </div>
      <div class="meta-block">
        <p>B/L No.</p><strong>${quote.bl_number ?? "TBD"}</strong><br>
        <p style="margin-top:6px">Carrier</p><strong>${quote.carrier ?? "TBD"}</strong><br>
        <p style="margin-top:6px">ETD / ETA</p>
        <strong>${quote.etd ?? "TBD"} / ${quote.eta ?? "TBD"}</strong>
      </div>
    </div>

    <h2>Charges</h2>
    <table>
      <tr><th>Description</th><th class="text-right">Amount (USD)</th></tr>
      <tr>
        <td>Ocean Freight – ${quote.origin_port} → ${quote.dest_port} (${quote.container_type})</td>
        <td class="text-right">${formatUSD(leg2)}</td>
      </tr>
      <tr>
        <td>US Domestic Trucking to ${quote.delivery_address ?? quote.delivery_state ?? "destination"}</td>
        <td class="text-right">${formatUSD(leg3)}</td>
      </tr>
      <tr class="total-row">
        <td class="text-right">Total Due (USD)</td>
        <td class="text-right">${formatUSD(leg2 + leg3)}</td>
      </tr>
    </table>

    <div class="signature-block">
      <div class="signature-line">Authorized Signature – TBP Auto Co., Ltd.</div>
    </div>
  `
  );
}

export function printServiceInvoice(quote: Quote) {
  const leg1Vnd = quote.leg1_cost_vnd ?? 0;
  const handlingFee = 500000;
  const totalVnd = leg1Vnd + handlingFee;

  openPrintWindow(
    `Service Invoice – ${quote.id}`,
    `
    <h1>SERVICE INVOICE</h1>

    <div class="meta-grid">
      <div class="meta-block">
        <p>From</p><strong>TBP Auto Co., Ltd.</strong><br>
        <span style="font-size:12px;color:#374151">Hai Phong Industrial Zone, Vietnam</span>
      </div>
      <div class="meta-block">
        <p>Invoice No.</p><strong>${quote.id}-SVC</strong><br>
        <p style="margin-top:6px">Date</p>
        <strong>${new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })}</strong>
      </div>
      <div class="meta-block">
        <p>To</p><strong>An Thai Co., Ltd.</strong>
      </div>
      <div class="meta-block">
        <p>Reference PO</p><strong>${quote.po_number ?? quote.id}</strong><br>
        <p style="margin-top:6px">Goods</p><strong>${quote.products ?? "Auto Parts"}</strong>
      </div>
    </div>

    <h2>Service Charges</h2>
    <table>
      <tr><th>Description</th><th class="text-right">Amount (VND)</th></tr>
      <tr>
        <td>Inland Trucking – Factory → Hai Phong Port (${quote.container_type})</td>
        <td class="text-right">${formatVND(leg1Vnd)}</td>
      </tr>
      <tr>
        <td>Documentation & Customs Handling Fee</td>
        <td class="text-right">${formatVND(handlingFee)}</td>
      </tr>
      <tr class="total-row">
        <td class="text-right">Total Due (VND)</td>
        <td class="text-right">${formatVND(totalVnd)}</td>
      </tr>
    </table>

    <p style="margin-top:12px;font-size:12px;color:#6b7280">
      Payment due within 30 days of invoice date.
    </p>

    <div class="signature-block">
      <div class="signature-line">Authorized Signature – TBP Auto Co., Ltd.</div>
    </div>
  `
  );
}

export function printCertificateOfOrigin(quote: Quote) {
  openPrintWindow(
    `Certificate of Origin – ${quote.id}`,
    `
    <h1>CERTIFICATE OF ORIGIN</h1>
    <p style="font-size:12px;color:#6b7280;margin-bottom:20px">
      Issued under the authority of TBP Auto Co., Ltd., Vietnam
    </p>

    <div class="meta-grid">
      <div class="meta-block">
        <p>Exporter (Name, Address)</p>
        <strong>TBP Auto Co., Ltd.</strong><br>
        <span style="font-size:12px;color:#374151">Hai Phong Industrial Zone, Vietnam</span>
      </div>
      <div class="meta-block">
        <p>C/O Reference No.</p><strong>${quote.id}-CO</strong><br>
        <p style="margin-top:6px">Date of Issue</p>
        <strong>${new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })}</strong>
      </div>
      <div class="meta-block">
        <p>Consignee (Name, Address)</p>
        <strong>${quote.customer_name}</strong><br>
        <span style="font-size:12px;color:#374151">${quote.delivery_address ?? ""}, ${quote.delivery_state ?? "USA"}</span>
      </div>
      <div class="meta-block">
        <p>Means of Transport</p><strong>${quote.carrier ?? "TBD"} – ${quote.container_type}</strong><br>
        <p style="margin-top:6px">Port of Loading</p><strong>Hai Phong, Vietnam (VNHPH)</strong><br>
        <p style="margin-top:6px">Port of Discharge</p><strong>${quote.dest_port}, USA</strong>
      </div>
    </div>

    <h2>Goods Description</h2>
    <table>
      <tr>
        <th>HS Code</th>
        <th>Description of Goods</th>
        <th>Country of Origin</th>
        <th>Gross Weight</th>
        <th>No. of Packages</th>
      </tr>
      <tr>
        <td>8708.xx</td>
        <td>${quote.products ?? "Auto Parts"}</td>
        <td><strong>VIETNAM</strong></td>
        <td>TBD kg</td>
        <td>TBD</td>
      </tr>
    </table>

    <p style="margin-top:20px;font-size:12px;line-height:1.6">
      The undersigned hereby declares that the above details and statements are correct,
      that all goods were <strong>produced in Vietnam</strong>, and that they comply with
      the origin requirements for export to the United States of America.
    </p>

    <div style="display:grid;grid-template-columns:1fr 1fr;gap:40px;margin-top:48px">
      <div class="signature-line">Authorized Signature & Stamp<br>TBP Auto Co., Ltd.</div>
      <div class="signature-line">Certified by Chamber of Commerce<br>(if applicable)</div>
    </div>
  `
  );
}
